spring:
  datasource:
    url: jdbc:h2:mem:demodb
    #url: jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 8081