server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:  ${oauth2.github.clientId}
            clientSecret: ${oauth2.github.clientSecret}
          google:
            clientId: ${oauth2.google.clientId}
            clientSecret: ${oauth2.google.clientSecret}